---
timezone: 'Europe/Stockholm'
locale: 'se_SE.UTF-8'
keymap: 'sv-latin1'

users:
  - username: 'par'
    real_name: 'Pär Degerman'
    email: 'par@degerman.org'
    shell: '/bin/bash'
    password: ''

super_users:
  - par

default_groups:
  - users

su_groups:
  - wheel
  - docker
  - ssh
