---
- name: install dmenu
  pacman:
    name:
      - dmenu
  become: true

- name: clone PKGBUILDS
  command:
    argv:
      - /usr/bin/git
      - clone
      - https://github.com/pardegerman/arch-packages.git
    chdir: /home/{{ archlinux_username }}/src
  become: true
  become_user: "{{ archlinux_username }}"

- name: build st
  command:
    argv:
      - /usr/bin/makepkg
      - -cC
    chdir: /home/{{ archlinux_username }}/src/arch-packages/st
  become: true
  become_user: "{{ archlinux_username }}"

- name: install st
  command:
    argv:
      - /usr/bin/pacman
      - -U
      - /home/{{ archlinux_username }}/src/dwm/st-*.tar.zst
  become: true

- name: build dwm
  command:
    argv:
      - /usr/bin/makepkg
      - -cC
    chdir: /home/{{ archlinux_username }}/src/arch-packages/dwm
  become: true
  become_user: "{{ archlinux_username }}"

- name: install dwm
  command: 
    argv:
      - /usr/bin/pacman 
      - -U
      - /home/{{ archlinux_username }}/src/dwm/dwm-*.tar.zst
  become: true
