---
- name: install dmenu
  pacman:
    name:
      - dmenu
  become: true

- name: clone PKGBUILDS
  command:
    argv:
      - /usr/bin/git
      - clone
      - https://github.com/pardegerman/arch-packages.git
    chdir: /home/{{ archlinux_username }}/src
  become: true
  become_user: "{{ archlinux_username }}"

- name: build st
  command:
    argv:
      - /usr/bin/makepkg
      - -cC
    chdir: /home/{{ archlinux_username }}/src/arch-packages/st
  become: true
  become_user: "{{ archlinux_username }}"

- name: install st
  pacman:
    name: "{{ item }}"
  with_fileglob: /home/{{ archlinux_username }}/src/arch-packages/st/st-*.pkg.tar.zst
  become: true

- name: build dwm
  command:
    argv:
      - /usr/bin/makepkg
      - -cC
    chdir: /home/{{ archlinux_username }}/src/arch-packages/dwm
  become: true
  become_user: "{{ archlinux_username }}"

- name: install dwm
  pacman: 
    name: "{{ item }}"
  with_fileglob: /home/{{ archlinux_username }}/src/arch-packages/dwm/dwm-*.pkg.tar.zst
  become: true

- name: configure {{ archlinux_username }} to use dwm
  copy:
    dest: /home/{{ archlinux_username }}/.dmrc
    content: |
      [Desktop]
      Session=dwm
    mode: 0644
    owner: par
    group: users

