---
- name: install lightdm
  pacman:
    name:
      - lightdm
  become: true

- name: install greeter
  aur: 
    name: lightdm-mini-greeter
    user: "{{ archlinux_username }}"

- name: configure lightdm
  copy: src=lightdm/{{ item.src }} dest=/etc/lightdm/{{ item.dest }}
  with_items:
    - { src: 'lightdm.conf', dest: '.' }
    - { src: 'lightdm.conf.d/20-greeter.conf', dest: 'lightdm.conf.d/' }
    - { src: 'lightdm.conf.d/60-xdmcp.conf', dest: 'lightdm.conf.d/' }
    - { src: 'lightdm.conf.d/70-vnc.conf', dest: 'lightdm.conf.d/' }

- name: configure greeter
  template:
    src: lightdm-mini-greeter.conf
    dest: /etc/lightdm/lightdm-mini-greeter.conf

- name: enable lightdm
  systemd:
    name: lightdm
    state: enabled
