---
- name: install lightdm
  pacman:
    name:
      - lightdm
  become: true

- name: install greeter
  aur: 
    name: lightdm-mini-greeter
    user: "{{ archlinux_username }}"

- name: configure lightdm
  copy: src=lightdm/{{ item }} dest=/etc/lightdm/
  with_items:
    - lightdm.conf
    - lightdm.conf.d/60-xdmcp.conf
    - lightdm.conf.d/70-vnc.conf

- name: configure greeter
  copy: src=lightdm/{{ item }} dest=/etc/lightdm/
  with_items:
    - lightdm-mini-greeter.conf
    - lightdm.conf.d/20-greeter.conf
