---
- name: install lightdm
  pacman:
    name:
      - lightdm
  become: true

- name: install greeter
  aur: 
    name: lightdm-mini-greeter
    user: "{{ archlinux_username }}"

- name: configure lightdm
  copy: src=lightdm/lightdm.conf dest=/etc/lightdm/
  copy: src=lightdm/lighdm.conf.d/{{ item }} dest=/etc/lightdm/lightdm.conf.d/
    - 60-xdmcp.conf
    - 70-vnc.conf

- name: configure greeter
  copy: 
    src: lightdm/lightdm-mini-greeter.conf 
    dest: /etc/lightdm/
  copy:
    src: lightdm/lightdm-conf.d/20-greeter.conf
    dest: /etc/lightdm/lightdm.conf.d/
