---
- name: install x
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
  become: true

- name: install fonts
  pacman:
    name:
      - ttf-hack
      - ttf-joypixels
      - ttf-nerd-fonts-symbols-mono
      - adobe-source-code-pro-fonts
      - adobe-source-han-sans-jp-fonts
      - noto-fonts
      - noto-fonts-emoji
      - powerline-fonts
      - ttf-dejavu
      - ttf-droid
      - ttf-inconsolata
      - ttf-liberation
  become: true

- name: install tools
  pacman:
    name:
      - arandr
      - lxrandr
      - xclip
  become: true

- name: install GUI themes
  pacman:
    name:
      - elementary-icon-theme
      - gnome-themes-extra
      - lxappearance
      - xcursor-premium
  become: true
