---
- name: restart iptables
  systemd:
    name: iptables
    state: restarted
  become: true

- name: restart openssh server
  systemd:
    name: sshd
    state: restarted
  when: archlinux_enable_openssh_server
  become: true
