---
- name: Examine if we need to regenerate host keys
  stat:
    path: /etc/ssh/ssh_host_keys_regenerated
    get_checksum: false
    get_md5: false
  register: host_keys

- name: Remove Existing Keys
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/ssh/ssh_host_dsa_key
    - /etc/ssh/ssh_host_dsa_key.pub
    - /etc/ssh/ssh_host_rsa_key
    - /etc/ssh/ssh_host_rsa_key.pub
    - /etc/ssh/ssh_host_ed25519_key
    - /etc/ssh/ssh_host_ed25519_key.pub
    - /etc/ssh/ssh_host_ecdsa_key
    - /etc/ssh/ssh_host_ecdsa_key.pub
  when: host_keys.stat.exists == False

- name: Regenerate DSA Keys
  command: /usr/bin/ssh-keygen -t dsa -o -a 100 -f /etc/ssh/ssh_host_dsa_key -N ''
  args:
    creates: /etc/ssh/ssh_host_dsa_key
  when: host_keys.stat.exists == False
  notify: Restart ssh

- name: Regenerate RSA Keys
  command: /usr/bin/ssh-keygen -t rsa -b 4096 -o -a 100 -f /etc/ssh/ssh_host_rsa_key -N ''
  args:
    creates: /etc/ssh/ssh_host_rsa_key
  when: host_keys.stat.exists == False
  notify: Restart ssh

- name: Regenerate ed25519 Key
  command: /usr/bin/ssh-keygen -t ed25519 -o -a 100 -f /etc/ssh/ssh_host_ed25519_key -N ''
  args:
    creates: /etc/ssh/ssh_host_ed25519_key
  when: host_keys.stat.exists == False
  notify: Restart ssh

- name: Regenerate ecdsa Key
  command: /usr/bin/ssh-keygen -t ecdsa -b 521 -o -a 100 -f /etc/ssh/ssh_host_ecdsa_key -N ''
  args:
    creates: /etc/ssh/ssh_host_ecdsa_key
  when: host_keys.stat.exists == False
  notify: Restart ssh

- name: Write Regenerate File
  lineinfile:
    dest: /etc/ssh/ssh_host_keys_regenerated
    line: "Host keys regenerated."
    state: present
    create: true
    owner: root
    group: root
    mode: 0644
  when: host_keys.stat.exists == False
