---
- name: Add user primary groups
  group:
    name: "{{ item.username }}"
    state: present
  with_items: "{{ users }}"

- name: Add additional groups
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ default_groups }}"
    - "{{ su_groups }}"

- name: Create users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.real_name }}"
    group: "{{ item.username }}"
    shell: "{{ item.shell }}"
    password: "{{ item.password }}"
    create_home: true
  with_items: "{{ users }}"

- name: Add users to the default groups
  user:
    name: "{{ item[0].username }}"
    groups: "{{ item[1] }}"
    append: true
  with_nested:
    - "{{ users }}"
    - "{{ default_groups }}"

- name: Add super users to additional groups
  user:
    name: "{{ item[0] }}"
    groups: "{{ item[1] }}"
    append: true
  with_nested: 
    - "{{ super_users }}"
    - "{{ su_groups }}"
