---
- name: refresh pacman cache
  pacman:
    update_cache: true

- name: restart paccache
  service:
    name: paccache.timer
    state: restarted

- name: reload systemd config
  command: systemctl daemon-reload
