---
- name: Setup pacman.conf
  template:
    src: etc--pacman.conf.j2
    dest: /etc/pacman.conf
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - refresh pacman cache

- name: Install pacman-contrib
  pacman:
    name: "pacman-contrib"
    state: present

- name: Create pacman hook directory
  file:
    name: /etc/pacman.d/hooks
    state: directory

- name: Setup pacman mirror list update hook
  template:
    src: etc-pacman.d-hooks--mirrorlist.hook.j2
    dest: /etc/pacman.d/hooks/mirrorlist.hook
    owner: root
    group: root
    mode: 0644

- name: Setup pacman cache cleanup service
  template:
    src: etc-systemd-system--paccache.service.j2
    dest: /etc/systemd/system/paccache.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd config

- name: Setup pacman cache cleanup timer
  template:
    src: etc-systemd-system--paccache.timer.j2
    dest: /etc/systemd/system/paccache.timer
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd config
    - restart paccache

- name: Enable and start pacman cache cleanup timer
  service:
    name: paccache.timer
    enabled: true
    state: started
