---
- name: install git
  pacman:
    name: git
  become: true

- name: configure git name
  git_config:
    name: user.name
    value: "{{ archlinux_user_real_name }}"
    scope: global
  become: true
  become_user: "{{ archlinux_username }}"

- name: configure git email
  git_config:
    name: user.email
    value: "{{ archlinux_user_email }}"
    scope: global
  become: true
  become_user: "{{ archlinux_username }}"
