---
- name: update pacman cache
  pacman:
    update_cache: true
  become: true

- name: install pacman tools
  pacman:
    name: 
      - pacman-contrib
      - reflector
  become: true

- name: update pacman mirrorlist
  script: update-mirrorlist.sh
  become: true

- name: install base metapackage
  pacman:
    name:
      - base
      - base-devel
  become: true

- name: perform full upgrade
  pacman:
    upgrade: true
    update_cache: true
  become: true
