---
- name: install vim
  pacman:
    name: vim
  become: true

- name: configure .vimrc
  copy:
    src: basic.vim
    dest: /home/{{ archlinux_username }}/.vimrc
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0644
  become: true
  become_user: "{{ archlinux_username }}"
